"""
Automated YouTube cookie refresher using Playwright.
Runs every REFRESH_HOURS (default 72 = 3 days).
Exports fresh Netscape-format cookies.txt for yt-dlp.
"""
import os
import time
import subprocess
from pathlib import Path

COOKIE_FILE = "/app/cookies.txt"
REFRESH_HOURS = int(os.getenv("REFRESH_HOURS", "72"))
TEST_URL = "https://www.youtube.com/watch?v=jfKfPfyJRdk"


def refresh_cookies():
    """Use Playwright headless Chromium to get fresh YouTube cookies."""
    print("[COOKIES] Refreshing YouTube cookies...")
    try:
        from playwright.sync_api import sync_playwright

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            context = browser.new_context()
            page = context.new_page()

            page.goto("https://www.youtube.com", wait_until="networkidle", timeout=30000)
            time.sleep(3)

            cookies = context.cookies()
            browser.close()

        # Write Netscape cookie format (yt-dlp compatible)
        written = 0
        with open(COOKIE_FILE, "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Auto-generated by cookie_refresher\n\n")
            for c in cookies:
                if "youtube" in c.get("domain", "") or "google" in c.get("domain", ""):
                    secure = "TRUE" if c.get("secure", False) else "FALSE"
                    expires = int(c.get("expires", 0))
                    domain = c.get("domain", "")
                    if not domain.startswith("."):
                        domain = "." + domain
                    f.write(
                        f"{domain}\tTRUE\t{c.get('path', '/')}\t"
                        f"{secure}\t{expires}\t{c['name']}\t{c['value']}\n"
                    )
                    written += 1

        print(f"[COOKIES] Saved {written} YouTube/Google cookies to {COOKIE_FILE}")

        # Verify cookies work with yt-dlp
        result = subprocess.run(
            ["yt-dlp", "--cookies", COOKIE_FILE, "--get-url", "-f", "best", TEST_URL],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            print("[COOKIES] Verification PASSED — cookies working!")
            return True
        else:
            print(f"[COOKIES] Verification FAILED — {result.stderr[:200]}")
            return False

    except Exception as e:
        print(f"[COOKIES] Error: {e}")
        return False


def main():
    print(f"[COOKIES] Auto-refresh every {REFRESH_HOURS} hours")
    print(f"[COOKIES] Cookie file: {COOKIE_FILE}")

    while True:
        cookie_path = Path(COOKIE_FILE)

        # Check if cookies exist and are fresh
        if cookie_path.exists():
            age_hours = (time.time() - cookie_path.stat().st_mtime) / 3600
            if age_hours < REFRESH_HOURS:
                print(f"[COOKIES] Still fresh ({age_hours:.1f}h old, refresh at {REFRESH_HOURS}h)")
                time.sleep(3600)  # check again in 1 hour
                continue

        # Refresh needed
        success = refresh_cookies()
        if success:
            print(f"[COOKIES] Next refresh in {REFRESH_HOURS} hours")
            time.sleep(REFRESH_HOURS * 3600)
        else:
            print("[COOKIES] Failed, retrying in 1 hour")
            time.sleep(3600)


if __name__ == "__main__":
    main()
